// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// This file is automatically generated by otelc pin for tracking instrumentations.
// Additional instrumentation imports may be added manually.

//go:build tools

//go:generate go run github.com/open-telemetry/opentelemetry-go-compile-instrumentation/tool/cmd/otelc pin --generate
package tools

// This app only uses net/http instrumentation, and excludes gin instrumentation.
import (
	_ "github.com/open-telemetry/opentelemetry-go-compile-instrumentation/tool/cmd/otelc"

	_ "github.com/open-telemetry/opentelemetry-go-compile-instrumentation/instrumentation/net/http/server"
)
