codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: auto        # compare to base
        threshold: 1%       # allow small drops
        informational: true # don't fail PRs on project drop
    patch:
      default:
        target: auto
        threshold: 0.1%     # require the change itself to be covered

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: yes
