// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

package instrument

import (
	"fmt"
	"os"
	"path/filepath"

	"go.opentelemetry.io/otelc/tool/util"
)

// pkgRuntimeImportPath is the import path of the pkg/runtime package that
// declares OtelcVersion. We inject a synthetic init() into this package at
// compile time to bake in the exact otelc version.
const pkgRuntimeImportPath = "go.opentelemetry.io/otelc/pkg/runtime"

// distroVersionFileContent is the Go source that overwrites OtelcVersion with
// the compile-time otelc version string.
const distroVersionFileContent = `// Code generated by otelc. DO NOT EDIT.
// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

package runtime

func init() { OtelcVersion = %q }
`

// injectDistroVersion generates a synthetic Go source file in workDir that sets
// runtime.OtelcVersion to the live otelc version (util.Version), then appends
// the file to the compile command. It is a no-op for every package except
// go.opentelemetry.io/otelc/pkg/runtime.
func (ip *InstrumentPhase) injectDistroVersion() error {
	pkgPath := util.FindFlagValue(ip.compileArgs, "-p")
	if pkgPath != pkgRuntimeImportPath {
		return nil
	}

	content := fmt.Sprintf(distroVersionFileContent, util.Version)

	outFile := filepath.Join(ip.workDir, "otelc.distro_version.go")
	if err := os.WriteFile(outFile, []byte(content), 0o600); err != nil {
		return err
	}

	ip.addCompileArg(outFile)
	ip.keepForDebug(outFile)
	ip.Info("Injected distro version into pkg/runtime", "version", util.Version, "file", outFile)
	return nil
}
