# See: https://github.com/DavidAnson/markdownlint/blob/main/README.md
# Default state for all rules
default: true

# ul-style
MD004: false

# hard-tabs
MD010: false

# line-length
MD013:
  line_length: 100
  strict: false
  code_blocks: false
  tables: false
  code_block_line_length: 80

# no-duplicate-header
MD024:
  siblings_only: true

#single-title
MD025: false

# ol-prefix
MD029:
  style: ordered

# no-inline-html
MD033: false

# fenced-code-language
MD040: false
