// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

package setup

import (
	"context"
	"fmt"
	"maps"
	"os"
	"path/filepath"
	"slices"

	"github.com/dave/dst"

	"go.opentelemetry.io/otelc/tool/ex"
	"go.opentelemetry.io/otelc/tool/internal/ast"
	"go.opentelemetry.io/otelc/tool/internal/instrument"
	"go.opentelemetry.io/otelc/tool/internal/rule"
	"go.opentelemetry.io/otelc/tool/util"
)

const (
	otelcRuntimeFile = "otelc.runtime.go"
)

// runtimePackage describes the package that receives a generated
// otelc.runtime.go: where it sits on disk, how it is imported, and the package
// name the generated file must declare.
type runtimePackage struct {
	dir        string
	importPath string
	name       string
}

//nolint:gochecknoglobals // This is a constant
var requiredImports = map[string]string{
	"runtime/debug": "_otel_debug", // The getstack function depends on runtime/debug
	"log":           "_otel_log",   // The printstack function depends on log
	"unsafe":        "_",           // The golinkname tag depends on unsafe
}

func genImportDecl(funcRules []*rule.InstFuncRule, fileRules []*rule.InstFileRule) []dst.Decl {
	var imports map[string]string
	if len(funcRules) > 0 {
		imports = maps.Clone(requiredImports) // clone required imports to avoid mutating the global map
		for _, m := range funcRules {
			imports[m.Path] = ast.IdentIgnore
		}
	} else {
		imports = make(map[string]string)
	}
	for _, m := range fileRules {
		imports[m.Path] = ast.IdentIgnore
	}
	importDecls := make([]dst.Decl, 0, len(imports))
	// Sort the keys to ensure deterministic order
	for _, k := range slices.Sorted(maps.Keys(imports)) {
		importDecls = append(importDecls, ast.ImportDecl(imports[k], k))
	}
	return importDecls
}

func genVarDecl(matched []*rule.InstFuncRule) []dst.Decl {
	decls := make([]dst.Decl, 0, len(matched))
	uniquePath := map[string]bool{}
	for i, m := range matched {
		if _, ok := uniquePath[m.Path]; ok {
			continue
		}
		uniquePath[m.Path] = true
		// First variable declaration
		// //go:linkname _getstack%d %s.OtelGetStackImpl
		// var _getstack%d = _otel_debug.Stack
		value := ast.SelectorExpr(ast.Ident("_otel_debug"), "Stack")
		getStackVar := ast.VarDecl(fmt.Sprintf("_getstack%d", i), value)
		getStackVar.Decs = dst.GenDeclDecorations{
			NodeDecs: ast.LineComments(
				fmt.Sprintf("//go:linkname _getstack%d %s.OtelGetStackImpl", i, m.Path)),
		}
		// Second variable declaration
		// //go:linkname _printstack%d %s.OtelPrintStackImpl
		// var _printstack%d = func (bt []byte){ _otel_log.Print(string(bt)) }
		// build: string(bt)
		stringCall := &dst.CallExpr{
			Fun:  ast.Ident("string"),
			Args: []dst.Expr{ast.Ident("bt")},
		}
		// build: _otel_log.Print(string(bt))
		printCall := &dst.CallExpr{
			Fun:  ast.SelectorExpr(ast.Ident("_otel_log"), "Print"),
			Args: []dst.Expr{stringCall},
		}
		// build: func (bt []byte) { _otel_log.Print(string(bt)) }
		printStackFunc := &dst.FuncLit{
			Type: &dst.FuncType{
				Params: &dst.FieldList{
					List: []*dst.Field{
						ast.Field("bt", ast.ArrayType(ast.Ident("byte"))),
					},
				},
			},
			Body: ast.BlockStmts(ast.ExprStmt(printCall)),
		}
		printStackVar := ast.VarDecl(fmt.Sprintf("_printstack%d", i), printStackFunc)
		printStackVar.Decs = dst.GenDeclDecorations{
			NodeDecs: ast.LineComments(
				fmt.Sprintf("//go:linkname _printstack%d %s.OtelPrintStackImpl", i, m.Path)),
		}
		decls = append(decls, getStackVar, printStackVar)
	}
	return decls
}

func buildOtelcRuntimeAst(decls []dst.Decl, packageName string) *dst.File {
	const comment = "// This file is generated by the opentelemetry-go-compile-instrumentation tool. DO NOT EDIT."
	return &dst.File{
		Name: ast.Ident(packageName),
		Decs: dst.FileDecorations{
			NodeDecs: ast.LineComments(comment),
		},
		Decls: decls,
	}
}

// runtimeContributors returns a deterministic, deduplicated list of rule names
// that contributed to the generation of otelc.runtime.go. Deduplication is based
// on stable rule identity rather than display name alone so distinct rules with
// identical display names are not merged.
func runtimeContributors(funcRules []*rule.InstFuncRule, fileRules []*rule.InstFileRule) []string {
	var contributors []string
	seen := make(map[string]struct{})

	for _, r := range funcRules {
		name := r.GetName()
		if name == "" {
			name = r.Func
		}
		if name == "" {
			name = r.Path
		}
		// Distinct func rules are identified by their name and content identity.
		id := fmt.Sprintf("func:%s:%s", r.GetName(), r.Identity())
		if _, ok := seen[id]; ok {
			continue
		}
		seen[id] = struct{}{}
		contributors = append(contributors, name)
	}

	for _, r := range fileRules {
		name := r.GetName()
		if name == "" {
			name = r.File
		}
		if name == "" {
			name = r.Path
		}
		// Distinct file rules are identified by their name, path, and file.
		id := fmt.Sprintf("file:%s:%s:%s", r.GetName(), r.Path, r.File)
		if _, ok := seen[id]; ok {
			continue
		}
		seen[id] = struct{}{}
		contributors = append(contributors, name)
	}

	slices.Sort(contributors)
	return contributors
}

func (sp *setupPhase) writeRuntimeDiffForDebug(srcPath, pkgPath string, contributors []string) {
	if !instrument.DiffDebugEnabled() {
		return
	}
	dest := filepath.Join(setupDebugDir(pkgPath), filepath.Base(srcPath)+".diff")
	header := instrument.FormatGeneratedFileHeader(otelcRuntimeFile, contributors)
	instrument.WriteAddedSourceDiff(dest, srcPath, header, sp.logger)
}

// removeRuntimeFile deletes the runtime file in pkgDir that an earlier setup
// generated from rules that no longer apply. A stale runtime file keeps its old
// imports and linkname declarations active in the build.
func (sp *setupPhase) removeRuntimeFile(ctx context.Context, pkgDir string) error {
	otelcRuntimeFilePath := filepath.Join(pkgDir, otelcRuntimeFile)
	if !util.PathExists(otelcRuntimeFilePath) {
		return nil
	}

	// Track the file first so that a later revert can restore it.
	if stateManager, found := stateManagerFromContext(ctx); found {
		if err := stateManager.Track(otelcRuntimeFilePath); err != nil {
			return err
		}
	}
	if err := os.Remove(otelcRuntimeFilePath); err != nil {
		return ex.Wrapf(err, "removing stale otelc runtime file %s", otelcRuntimeFilePath)
	}
	sp.Info("Removed stale otelc.runtime.go", "path", otelcRuntimeFilePath)

	return nil
}

// addDeps generates and writes otelc.runtime.go with required imports and variable
// declarations for OpenTelemetry instrumentation based on matched rules.
//
// Rules that keep their hook code in pkg itself are dropped, since a generated
// file cannot import the package it belongs to. `otelc go test ./...` selects
// such a package when the hooks live in the application module.
func (sp *setupPhase) addDeps(ctx context.Context, matched []*rule.InstRuleSet, pkg runtimePackage) error {
	funcRules := []*rule.InstFuncRule{}
	fileRules := []*rule.InstFileRule{}
	for _, m := range matched {
		for _, funcRule := range m.AllFuncRules() {
			if funcRule.Path != pkg.importPath {
				funcRules = append(funcRules, funcRule)
			}
		}
		for _, fileRule := range m.FileRules {
			if fileRule.Path != pkg.importPath {
				fileRules = append(fileRules, fileRule)
			}
		}
	}
	if len(funcRules) == 0 && len(fileRules) == 0 {
		return sp.removeRuntimeFile(ctx, pkg.dir)
	}

	// Add required imports
	importDecls := genImportDecl(funcRules, fileRules)
	// Generate the variable declarations that used by otel runtime
	varDecls := genVarDecl(funcRules)
	// build the ast
	root := buildOtelcRuntimeAst(append(importDecls, varDecls...), pkg.name)
	otelcRuntimeFilePath := filepath.Join(pkg.dir, otelcRuntimeFile)
	// Track file in state manager
	if stateManager, found := stateManagerFromContext(ctx); found {
		if err := stateManager.Track(otelcRuntimeFilePath); err != nil {
			return err
		}
	}
	// Write the ast to file
	if err := ast.WriteFileAtomic(otelcRuntimeFilePath, root); err != nil {
		return ex.Wrapf(err, "writing otelc runtime file %s", otelcRuntimeFilePath)
	}
	keepForDebug(ctx, otelcRuntimeFilePath, pkg.importPath)
	sp.writeRuntimeDiffForDebug(otelcRuntimeFilePath, pkg.importPath, runtimeContributors(funcRules, fileRules))
	sp.Info("Created otelc.runtime.go", "path", otelcRuntimeFilePath)
	return nil
}
