// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

package setup

import (
	"context"
	"errors"
	"fmt"
	"go/parser"
	"go/token"
	"io/fs"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"

	"github.com/dave/dst"
	"golang.org/x/mod/modfile"
	"golang.org/x/mod/module"
	"golang.org/x/mod/semver"
	"gopkg.in/yaml.v3"

	"github.com/open-telemetry/opentelemetry-go-compile-instrumentation/tool/ex"
	"github.com/open-telemetry/opentelemetry-go-compile-instrumentation/tool/internal/ast"
	"github.com/open-telemetry/opentelemetry-go-compile-instrumentation/tool/internal/pkgload"
	"github.com/open-telemetry/opentelemetry-go-compile-instrumentation/tool/util"
)

func removeImports(f *dst.File, importPaths map[string]bool) error {
	decls := make([]dst.Decl, 0, len(f.Decls))

	for _, decl := range f.Decls {
		genDecl, isGenDecl := decl.(*dst.GenDecl)
		if !isGenDecl || genDecl.Tok != token.IMPORT {
			decls = append(decls, decl)
			continue
		}

		specs := genDecl.Specs[:0]
		for _, spec := range genDecl.Specs {
			importSpec, isImportSpec := spec.(*dst.ImportSpec)
			if !isImportSpec {
				specs = append(specs, spec)
				continue
			}

			path, err := strconv.Unquote(importSpec.Path.Value)
			if err != nil {
				return ex.Wrapf(err, "failed to unquote import path %s", importSpec.Path.Value)
			}

			// skip the import we want to remove
			if _, removeImport := importPaths[path]; removeImport {
				continue
			}

			specs = append(specs, spec)
		}

		if len(specs) == 0 {
			// entire import decl became empty
			continue
		}

		genDecl.Specs = specs
		decls = append(decls, genDecl)
	}

	f.Decls = decls
	return nil
}

func generateDirective(opts PinOptions) string {
	args := []string{
		"//go:generate",
		"go",
		"run",
		util.OtelcToolCmdRoot,
		"pin",
		"--generate",
	}

	if !opts.Prune {
		args = append(args, "--prune=false")
	}
	if opts.Validate {
		args = append(args, "--validate")
	}

	return strings.Join(args, " ")
}

func updateGenerateDirective(f *dst.File, opts PinOptions) {
	// Nothing passed? Do not touch the directive at all.
	if opts.Generate == nil {
		return
	}

	comments := make([]string, 0, len(f.Decs.Start.All()))
	for _, comment := range f.Decs.Start.All() {
		// Drop any existing otelc pin directive. We will either
		// regenerate it or remove it entirely.
		const goGenerateDirectivePrefix = "//go:generate go run github.com/open-telemetry/opentelemetry-go-compile-instrumentation/tool/cmd/otelc pin"
		if strings.HasPrefix(comment, goGenerateDirectivePrefix) {
			continue
		}

		comments = append(comments, comment)
	}

	if *opts.Generate {
		comments = append(comments, generateDirective(opts))
	}

	f.Decs.Start.Clear()
	f.Decs.Start.Append(comments...)
}

func generateOtelInstrumentationGo(imports map[string]bool, opts PinOptions) *dst.File {
	importPaths := make([]string, 0, len(imports))
	for path := range imports {
		importPaths = append(importPaths, path)
	}
	slices.Sort(importPaths)

	importSpecs := make([]dst.Spec, 0, len(importPaths)+1)
	// Always include the otelc tool import
	importSpecs = append(importSpecs, &dst.ImportSpec{
		Name: ast.Ident(ast.IdentIgnore),
		Path: &dst.BasicLit{
			Kind:  token.STRING,
			Value: strconv.Quote(util.OtelcToolCmdRoot),
		},
		Decs: dst.ImportSpecDecorations{
			NodeDecs: dst.NodeDecs{
				After: dst.EmptyLine,
			},
		},
	})
	for _, path := range importPaths {
		importSpecs = append(importSpecs, &dst.ImportSpec{
			Name: ast.Ident(ast.IdentIgnore),
			Path: &dst.BasicLit{
				Kind:  token.STRING,
				Value: strconv.Quote(path),
			},
		})
	}

	comments := ast.LineComments(
		"// This file is automatically generated by otelc pin for tracking instrumentations.",
		"// Additional instrumentation imports may be added manually.",
		"\n",
		"//go:build tools",
	)

	// If generate is explicitly enabled, or not set at all, include the //go:generate directive.
	if opts.Generate == nil || *opts.Generate {
		comments.Start.Append(generateDirective(opts))
	}

	return &dst.File{
		Name: ast.Ident("tools"),
		Decs: dst.FileDecorations{
			NodeDecs: comments,
		},
		Decls: []dst.Decl{
			&dst.GenDecl{
				Tok:   token.IMPORT,
				Specs: importSpecs,
			},
		},
	}
}

type yamlRule struct {
	Target       string `yaml:"target"`
	VersionRange string `yaml:"version"`
}

func loadMinimalRules() (map[string][]yamlRule, error) {
	loaded := make(map[string][]yamlRule)

	rulesRoot := filepath.Join(util.GetBuildTempDir(), unzippedInstDir)
	err := filepath.WalkDir(rulesRoot, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !isRuleFile(d.Name()) {
			return nil
		}

		data, readErr := os.ReadFile(path) //nolint:gosec // walking compiler generated rules
		if readErr != nil {
			return ex.Wrapf(readErr, "reading rule file %s", path)
		}

		var rules map[string]yamlRule
		if yamlErr := yaml.Unmarshal(data, &rules); yamlErr != nil {
			return ex.Wrapf(yamlErr, "parsing rule file %s", path)
		}

		// Assume go.mod is in the same directory as the yaml.
		goModPath := filepath.Join(filepath.Dir(path), "go.mod")
		modFile, parseErr := parseGoMod(goModPath)
		if parseErr != nil {
			return ex.Wrapf(parseErr, "loading go.mod for %s", path)
		}

		loaded[modFile.Module.Mod.Path] = make([]yamlRule, 0, len(rules))
		for _, r := range rules {
			if r.Target == "" {
				continue
			}
			loaded[modFile.Module.Mod.Path] = append(loaded[modFile.Module.Mod.Path], r)
		}

		return nil
	})
	if err != nil {
		return nil, err
	}

	return loaded, nil
}

func ensureOtelcRequire(moduleDir, version string) (bool, error) {
	if module.IsPseudoVersion(version) {
		// Let go mod tidy handle pseudo-versions.
		return false, nil
	}

	goModPath := filepath.Join(moduleDir, "go.mod")
	data, readErr := os.ReadFile(goModPath)
	if readErr != nil {
		return false, readErr
	}

	f, parseErr := modfile.Parse(goModPath, data, nil)
	if parseErr != nil {
		return false, parseErr
	}

	for _, req := range f.Require {
		if req.Mod.Path == util.OtelcRoot && semver.Compare(req.Mod.Version, version) >= 0 {
			return false, nil
		}
	}

	if addErr := f.AddRequire(util.OtelcRoot, version); addErr != nil {
		return false, addErr
	}

	if writeErr := writeGoMod(goModPath, f); writeErr != nil {
		return false, writeErr
	}

	return true, nil
}

func findPinnedToolFiles(moduleDirs map[string]bool) (map[string]map[string]bool, error) {
	toolFiles := make(map[string]map[string]bool, len(moduleDirs))

	for moduleDir := range moduleDirs {
		toolFile, err := findToolFile(moduleDir)
		if err != nil {
			return nil, ex.Wrapf(err, "checking for existing tool file in %s", moduleDir)
		}
		if toolFile == "" {
			continue
		}

		// value stores imports that should be pruned from this root tool file
		toolFiles[toolFile] = make(map[string]bool)
	}

	return toolFiles, nil
}

func matchInstrumentationImports(deps []*Dependency, ruleset map[string][]yamlRule) map[string]bool {
	imports := make(map[string]bool)

	// Match only on target + version.
	for _, dep := range deps {
		for modPath, rules := range ruleset {
			for _, rule := range rules {
				if rule.Target != dep.ImportPath {
					continue
				}
				if !util.VersionInRange(dep.Version, rule.VersionRange) {
					continue
				}

				imports[modPath] = true
			}
		}
	}

	return imports
}

func updateToolFile(ctx context.Context, toolFile string, prunedImports map[string]bool, opts PinOptions) error {
	p := ast.NewAstParser()

	f, parseErr := p.Parse(toolFile, parser.ParseComments)
	if parseErr != nil {
		return ex.Wrapf(parseErr, "parsing tool file %s", toolFile)
	}

	if len(prunedImports) > 0 {
		if removeErr := removeImports(f, prunedImports); removeErr != nil {
			return ex.Wrapf(removeErr, "removing imports from %s", toolFile)
		}
	}

	updateGenerateDirective(f, opts)

	if writeErr := ast.WriteFileAtomic(toolFile, f); writeErr != nil {
		return writeErr
	}

	modified, ensureErr := ensureOtelcRequire(filepath.Dir(toolFile), util.Version)
	if ensureErr != nil {
		return ex.Wrapf(ensureErr, "ensuring otelc require in go.mod in %s", filepath.Dir(toolFile))
	}

	if len(prunedImports) > 0 || modified {
		if tidyErr := runModTidy(ctx, filepath.Dir(toolFile)); tidyErr != nil {
			return ex.Wrapf(tidyErr, "running go mod tidy in %s", filepath.Dir(toolFile))
		}
	}

	return nil
}

func collectToolFileImports(toolFile string, prunedImports map[string]bool) (map[string]bool, error) {
	p := ast.NewAstParser()
	f, parseErr := p.Parse(toolFile, parser.ImportsOnly)
	if parseErr != nil {
		return nil, ex.Wrapf(parseErr, "parsing tool file %s", toolFile)
	}

	imports := make(map[string]bool)
	for _, imp := range f.Imports {
		if imp.Name == nil || imp.Name.Name != ast.IdentIgnore {
			continue
		}

		importPath, unquoteErr := strconv.Unquote(imp.Path.Value)
		if unquoteErr != nil {
			return nil, ex.Wrapf(unquoteErr, "failed to unquote import path %s in %s", imp.Path.Value, toolFile)
		}
		if importPath == util.OtelcToolCmdRoot {
			continue
		}
		if prunedImports != nil && prunedImports[importPath] {
			continue
		}

		imports[importPath] = true
	}

	return imports, nil
}

func updatePinnedProjects(
	ctx context.Context,
	toolFiles map[string]map[string]bool,
	opts PinOptions,
) (*PinResult, error) {
	logger := util.LoggerFromContext(ctx)

	for toolFile, prunedImports := range toolFiles {
		imports, collectErr := collectToolFileImports(toolFile, prunedImports)
		if collectErr != nil {
			return nil, collectErr
		}

		if syncErr := syncDeps(ctx, imports, filepath.Dir(toolFile)); syncErr != nil {
			return nil, ex.Wrapf(syncErr, "syncing dependencies in %s", filepath.Dir(toolFile))
		}
	}

	walkErr := walkInstrumentation(
		ctx,
		slices.Collect(maps.Keys(toolFiles)),
		func(v *InstrumentationVisit) (bool, error) {
			pruneImport := func(reason error) {
				logger.WarnContext(ctx, "invalid instrumentation import",
					"importPath", v.ImportPath,
					"toolFile", v.ToolFile,
					"reason", reason)
				_, _ = fmt.Fprintf(
					os.Stderr,
					"Invalid instrumentation import %s from %s: %v\n",
					v.ImportPath,
					v.ToolFile,
					reason,
				)

				if _, isRootToolFile := toolFiles[v.ToolFile]; opts.Prune && isRootToolFile {
					toolFiles[v.ToolFile][v.ImportPath] = true
				}
			}

			if v.Error != nil {
				if errors.Is(v.Error, ErrNotInstrumentation) {
					pruneImport(v.Error)
					return false, nil
				}

				// Environment/module resolution problem.
				return false, v.Error
			}

			// Also validate that all rule files in the import are valid.
			if opts.Validate {
				for _, ruleFile := range v.Config.RuleFiles {
					content, readErr := os.ReadFile(ruleFile)
					if readErr != nil {
						pruneImport(ex.Wrapf(readErr, "reading %s", ruleFile))
						return false, nil
					}

					if _, parseErr := parseRuleFromYaml(content); parseErr != nil {
						pruneImport(parseErr)
						return false, nil
					}
				}
			}

			// Always recurse into nested tool files when they exist.
			return true, nil
		},
	)
	if walkErr != nil {
		return nil, walkErr
	}

	for toolFile, prunedImports := range toolFiles {
		if err := updateToolFile(ctx, toolFile, prunedImports, opts); err != nil {
			return nil, err
		}
	}

	return &PinResult{}, nil
}

func generatePinnedProjects(ctx context.Context, moduleDirs map[string]bool, opts PinOptions) (*PinResult, error) {
	logger := util.LoggerFromContext(ctx)

	// No tool file found? Try generating one.
	deps, findDepsErr := findDeps(ctx, opts.Args)
	if findDepsErr != nil {
		return nil, ex.Wrapf(findDepsErr, "finding dependencies")
	}

	ruleset, err := loadMinimalRules()
	if err != nil {
		return nil, ex.Wrapf(err, "loading instrumentation rules")
	}

	imports := matchInstrumentationImports(deps, ruleset)

	// Nothing to instrument? Warn and skip generating tool file.
	if len(imports) == 0 {
		_, _ = fmt.Fprintln(os.Stderr, "Warning: no instrumentations matched")
		logger.WarnContext(ctx, "no instrumentations matched, skipping generating tool file")
		return &PinResult{AllDeps: deps}, nil
	}

	// Generate otel.instrumentation.go file with imports for all matched rules.
	f := generateOtelInstrumentationGo(imports, opts)
	for moduleDir := range moduleDirs {
		path := filepath.Join(moduleDir, ToolFileCanonical)
		if writeErr := ast.WriteFileAtomic(path, f); writeErr != nil {
			return nil, ex.Wrapf(writeErr, "writing %s", path)
		}

		if _, ensureErr := ensureOtelcRequire(moduleDir, util.Version); ensureErr != nil {
			return nil, ex.Wrapf(ensureErr, "ensuring otelc require in go.mod in %s", moduleDir)
		}

		if syncErr := syncDeps(ctx, imports, moduleDir); syncErr != nil {
			return nil, ex.Wrapf(syncErr, "syncing dependencies in %s", moduleDir)
		}

		keepForDebug(ctx, path)
	}

	// Re-load dependencies after syncDeps has updated go.mod.
	deps, findDepsErr = findDeps(ctx, opts.Args)
	if findDepsErr != nil {
		return nil, ex.Wrapf(findDepsErr, "finding dependencies after sync")
	}

	return &PinResult{AllDeps: deps}, nil
}

type PinOptions struct {
	Prune    bool
	Validate bool
	Generate *bool
	Args     []string
}

type PinResult struct {
	AllDeps []*Dependency
}

// Pin generates or updates otel.instrumentation.go to pin instrumentation packages for the current module.
// It also returns a PinResult, which may optionally include a list of all dependencies found in the project
// (not just those with instrumentation). The PinResult can be used by later stages (setup) instead of
// re-parsing compile commands again.
func Pin(ctx context.Context, opts PinOptions) (*PinResult, error) {
	pkgs, getErr := getBuildPackages(ctx, opts.Args)
	if getErr != nil {
		return nil, ex.Wrapf(getErr, "getting build packages")
	}

	moduleDirs, findErr := pkgload.FindModuleDirs(ctx, pkgs)
	if findErr != nil {
		return nil, ex.Wrapf(findErr, "finding module directories")
	}

	toolFiles, findToolErr := findPinnedToolFiles(moduleDirs)
	if findToolErr != nil {
		return nil, findToolErr
	}

	extractErr := extractBundle()
	if extractErr != nil {
		return nil, ex.Wrapf(extractErr, "extracting otelc package")
	}

	// Existing otel.instrumentation.go / otelc.tool.go files found?
	// Validate and update them in-place.
	if len(toolFiles) > 0 {
		return updatePinnedProjects(ctx, toolFiles, opts)
	}

	// Otherwise, infer instrumentations from the dependency graph and
	// generate fresh tool files.
	return generatePinnedProjects(ctx, moduleDirs, opts)
}

// AutoPin is a convenience function that automatically backs up files before calling Pin,
// and returns a cleanup function to remove any generated otel.instrumentation.go files that did not exist before.
func AutoPin(ctx context.Context, moduleDirs map[string]bool, args []string) (*PinResult, func(), error) {
	logger := util.LoggerFromContext(ctx)

	if backupErr := backupFiles(ctx, moduleDirs); backupErr != nil {
		return nil, nil, ex.Wrapf(backupErr, "backing up files")
	}

	// Also remove generated otel.instrumentation.go if one did not exist before.
	filesToRemove := make([]string, 0, len(moduleDirs))
	for moduleDir := range moduleDirs {
		toolFile := filepath.Join(moduleDir, ToolFileCanonical)
		if !util.PathExists(toolFile) {
			filesToRemove = append(filesToRemove, toolFile)
		}
	}

	cleanup := func() {
		for _, f := range filesToRemove {
			if rmErr := os.Remove(f); rmErr != nil {
				logger.WarnContext(ctx, "failed to remove generated file", "path", f, "error", rmErr)
			}
		}
	}

	pinResult, pinErr := Pin(ctx, PinOptions{
		Prune: true,
		Args:  args,
	})

	return pinResult, cleanup, pinErr
}
