// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

package setup

import (
	"context"
	"errors"
	"fmt"
	"go/parser"
	"go/token"
	"io"
	"io/fs"
	"log/slog"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"

	"github.com/dave/dst"
	"golang.org/x/mod/modfile"
	"golang.org/x/mod/module"
	"golang.org/x/mod/semver"
	"gopkg.in/yaml.v3"

	"go.opentelemetry.io/otelc/tool/ex"
	"go.opentelemetry.io/otelc/tool/internal/ast"
	"go.opentelemetry.io/otelc/tool/internal/pkgload"
	"go.opentelemetry.io/otelc/tool/internal/rule"
	"go.opentelemetry.io/otelc/tool/util"
)

func removeImports(f *dst.File, importPaths map[string]bool) error {
	decls := make([]dst.Decl, 0, len(f.Decls))

	for _, decl := range f.Decls {
		genDecl, isGenDecl := decl.(*dst.GenDecl)
		if !isGenDecl || genDecl.Tok != token.IMPORT {
			decls = append(decls, decl)
			continue
		}

		specs := genDecl.Specs[:0]
		for _, spec := range genDecl.Specs {
			importSpec, isImportSpec := spec.(*dst.ImportSpec)
			if !isImportSpec {
				specs = append(specs, spec)
				continue
			}

			path, err := strconv.Unquote(importSpec.Path.Value)
			if err != nil {
				return ex.Wrapf(err, "failed to unquote import path %s", importSpec.Path.Value)
			}

			// skip the import we want to remove
			if _, removeImport := importPaths[path]; removeImport {
				continue
			}

			specs = append(specs, spec)
		}

		if len(specs) == 0 {
			// entire import decl became empty
			continue
		}

		genDecl.Specs = specs
		decls = append(decls, genDecl)
	}

	f.Decls = decls
	return nil
}

func generateDirective(opts PinOptions) string {
	args := []string{
		"//go:generate",
		"go",
		"tool",
		util.OtelcToolExe,
		"pin",
		"--generate",
	}

	if !opts.Prune {
		args = append(args, "--prune=false")
	}
	if opts.Validate {
		args = append(args, "--validate")
	}

	return strings.Join(args, " ")
}

func updateGenerateDirective(f *dst.File, opts PinOptions) {
	// Nothing passed? Do not touch the directive at all.
	if opts.Generate == nil {
		return
	}

	comments := make([]string, 0, len(f.Decs.Start.All()))
	for _, comment := range f.Decs.Start.All() {
		// Drop any existing otelc pin directive. We will either
		// regenerate it or remove it entirely.
		const goGenerateDirectivePrefix = "//go:generate go tool " + util.OtelcToolExe + " pin"
		if strings.HasPrefix(comment, goGenerateDirectivePrefix) {
			continue
		}

		comments = append(comments, comment)
	}

	if *opts.Generate {
		comments = append(comments, generateDirective(opts))
	}

	f.Decs.Start.Clear()
	f.Decs.Start.Append(comments...)
}

func generateOtelInstrumentationGo(imports map[string]bool, opts PinOptions) *dst.File {
	// Create a slice of import paths and sort them
	importPaths := sortedImportPaths(imports)

	// Use the sorted import paths to create import specs
	importSpecs := make([]dst.Spec, 0, len(importPaths))
	for _, path := range importPaths {
		importSpecs = append(importSpecs, &dst.ImportSpec{
			Name: ast.Ident(ast.IdentIgnore),
			Path: &dst.BasicLit{
				Kind:  token.STRING,
				Value: strconv.Quote(path),
			},
		})
	}

	comments := ast.LineComments(
		"// This file is automatically generated by otelc pin for tracking instrumentations.",
		"// Additional instrumentation imports may be added manually.",
		"\n",
		"//go:build tools",
	)

	// If generate is explicitly enabled, or not set at all, include the //go:generate directive.
	if opts.Generate == nil || *opts.Generate {
		comments.Start.Append(generateDirective(opts))
	}

	return &dst.File{
		Name: ast.Ident("tools"),
		Decs: dst.FileDecorations{
			NodeDecs: comments,
		},
		Decls: []dst.Decl{
			&dst.GenDecl{
				Tok:   token.IMPORT,
				Specs: importSpecs,
			},
		},
	}
}

type otelYAMLConfig struct {
	Instrumentations []string `yaml:"instrumentations"`
}

type fileBackup struct {
	path    string
	data    []byte
	mode    fs.FileMode
	existed bool
}

func sortedImportPaths(imports map[string]bool) []string {
	importPaths := make([]string, 0, len(imports))
	for path := range imports {
		importPaths = append(importPaths, path)
	}
	slices.Sort(importPaths)
	return importPaths
}

func sortedStringsMapKeys[V any](values map[string]V) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	slices.Sort(keys)
	return keys
}

func loadOtelYAMLImports(path string) (map[string]bool, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, ex.Wrapf(err, "reading %s", path)
	}

	var cfg otelYAMLConfig
	decoder := yaml.NewDecoder(strings.NewReader(string(data)))
	decoder.KnownFields(true)
	if decodeErr := decoder.Decode(&cfg); decodeErr != nil {
		return nil, ex.Wrapf(decodeErr, "parsing %s", path)
	}
	var extra any
	if decodeErr := decoder.Decode(&extra); decodeErr == nil {
		return nil, ex.Newf("%s: multiple YAML documents are not allowed", path)
	} else if !errors.Is(decodeErr, io.EOF) {
		return nil, ex.Wrapf(decodeErr, "parsing %s", path)
	}

	imports := make(map[string]bool, len(cfg.Instrumentations))
	for _, instrumentation := range cfg.Instrumentations {
		instrumentation = strings.TrimSpace(instrumentation)
		if instrumentation == "" {
			return nil, ex.Newf("%s: instrumentations must not contain empty import paths", path)
		}
		imports[instrumentation] = true
	}

	return imports, nil
}

func writeOtelYAMLImports(path string, imports map[string]bool) error {
	cfg := otelYAMLConfig{Instrumentations: sortedImportPaths(imports)}
	data, err := yaml.Marshal(&cfg)
	if err != nil {
		return ex.Wrapf(err, "marshalling %s", path)
	}
	info, err := os.Stat(path)
	if err != nil {
		return ex.Wrapf(err, "stating %s", path)
	}
	if err = util.WriteFileAtomic(path, data, info.Mode().Perm()); err != nil {
		return ex.Wrapf(err, "writing %s", path)
	}
	return nil
}

func loadToolFileImports(path string) (map[string]bool, error) {
	p := ast.NewAstParser()
	f, err := p.Parse(path, parser.ImportsOnly)
	if err != nil {
		return nil, ex.Wrapf(err, "parsing tool file %s", path)
	}
	paths, err := collectImports(path, f, make(map[string]bool))
	if err != nil {
		return nil, err
	}
	imports := make(map[string]bool, len(paths))
	for _, importPath := range paths {
		imports[importPath] = true
	}
	return imports, nil
}

func mergeImports(importSets ...map[string]bool) map[string]bool {
	merged := make(map[string]bool)
	for _, imports := range importSets {
		for importPath := range imports {
			merged[importPath] = true
		}
	}
	return merged
}

func backupFile(path string) (fileBackup, error) {
	info, err := os.Stat(path)
	if errors.Is(err, os.ErrNotExist) {
		return fileBackup{path: path}, nil
	}
	if err != nil {
		return fileBackup{}, ex.Wrapf(err, "stating %s", path)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return fileBackup{}, ex.Wrapf(err, "reading %s", path)
	}
	return fileBackup{path: path, data: data, mode: info.Mode(), existed: true}, nil
}

func restoreFiles(backups []fileBackup) error {
	var err error
	for _, backup := range backups {
		if backup.existed {
			err = ex.Join(err, os.WriteFile(backup.path, backup.data, backup.mode.Perm()))
		} else if removeErr := os.Remove(backup.path); removeErr != nil && !errors.Is(removeErr, os.ErrNotExist) {
			err = ex.Join(err, removeErr)
		}
	}
	return err
}

func restoreOtelYAMLValidationFiles(result *PinResult, pinErr error, backups []fileBackup) (*PinResult, error) {
	return result, ex.Join(pinErr, restoreFiles(backups))
}

type yamlRule struct {
	Target       string `yaml:"target"`
	VersionRange string `yaml:"version"`
}

func loadModuleRules(moduleDir, module string, loaded map[string][]yamlRule) error {
	return filepath.WalkDir(moduleDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if d.IsDir() {
			// Skip any submodules
			if path != moduleDir && util.PathExists(filepath.Join(path, "go.mod")) {
				return filepath.SkipDir
			}
			return nil
		}

		if !isRuleFile(d.Name()) {
			return nil
		}

		data, readErr := os.ReadFile(path) //nolint:gosec // walking embedded rules from extractOtelcBundle
		if readErr != nil {
			return ex.Wrapf(readErr, "reading rule file %s", path)
		}

		var rules map[string]yamlRule
		if unmarshalErr := yaml.Unmarshal(data, &rules); unmarshalErr != nil {
			return ex.Wrapf(unmarshalErr, "parsing rule file %s", path)
		}

		for _, r := range rules {
			if r.Target != "" {
				loaded[module] = append(loaded[module], r)
			}
		}

		return nil
	})
}

func loadMinimalRules(rulesRoot string) (map[string][]yamlRule, error) {
	loaded := make(map[string][]yamlRule)

	err := filepath.WalkDir(rulesRoot, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		// rulesRoot is instrumentation/
		// We want to load rules for submodules within instrumentation/
		// Look for go.mod nested within instrumentation/
		if d.IsDir() || d.Name() != "go.mod" || filepath.Dir(path) == rulesRoot {
			return nil
		}

		modFile, err := parseGoMod(path)
		if err != nil {
			return ex.Wrapf(err, "loading %s", path)
		}

		return loadModuleRules(filepath.Dir(path), modFile.Module.Mod.Path, loaded)
	})
	if err != nil {
		return nil, err
	}

	return loaded, nil
}

func ensureOtelcRequireVersion(f *modfile.File, version string) (bool, error) {
	if !semver.IsValid(version) || version == "v0.0.0" || module.IsPseudoVersion(version) {
		return false, nil
	}

	for _, req := range f.Require {
		if req.Mod.Path != util.OtelcRoot {
			continue
		}

		if semver.Compare(req.Mod.Version, version) >= 0 {
			return false, nil
		}
		break
	}

	if err := f.AddRequire(util.OtelcRoot, version); err != nil {
		return false, err
	}

	return true, nil
}

func ensureOtelcRequire(moduleDir, version string) (bool, error) {
	goModPath := filepath.Join(moduleDir, "go.mod")
	data, err := os.ReadFile(goModPath)
	if err != nil {
		return false, err
	}

	f, err := modfile.Parse(goModPath, data, nil)
	if err != nil {
		return false, err
	}

	modified := false

	hasTool := false
	for _, tool := range f.Tool {
		if tool.Path == util.OtelcToolCmdRoot {
			hasTool = true
			break
		}
	}

	if !hasTool {
		if addErr := f.AddTool(util.OtelcToolCmdRoot); addErr != nil {
			return false, addErr
		}
		modified = true
	}

	added, ensureErr := ensureOtelcRequireVersion(f, version)
	if ensureErr != nil {
		return false, ensureErr
	}
	modified = modified || added

	if !modified {
		return false, nil
	}

	if writeErr := writeGoMod(goModPath, f); writeErr != nil {
		return false, writeErr
	}

	return true, nil
}

func matchInstrumentationImports(deps []*Dependency, ruleset map[string][]yamlRule) map[string]bool {
	imports := make(map[string]bool)

	// Match only on target + version.
	for _, dep := range deps {
		for modPath, rules := range ruleset {
			for _, r := range rules {
				switch {
				case rule.IsRootTarget(r.Target):
					// always add root targets
					// they will be further matched in setup phase
					imports[modPath] = true
					continue
				case rule.IsGlobTarget(r.Target):
					if !rule.MatchGlobTarget(r.Target, dep.ImportPath) {
						continue
					}
				case r.Target != dep.ImportPath:
					continue
				}

				if !util.VersionInRange(dep.Version, r.VersionRange) {
					continue
				}

				imports[modPath] = true
			}
		}
	}

	return imports
}

func updateToolFile(ctx context.Context, toolFile string, prunedImports map[string]bool, opts PinOptions) error {
	p := ast.NewAstParser()

	f, parseErr := p.Parse(toolFile, parser.ParseComments)
	if parseErr != nil {
		return ex.Wrapf(parseErr, "parsing tool file %s", toolFile)
	}

	if len(prunedImports) > 0 {
		if removeErr := removeImports(f, prunedImports); removeErr != nil {
			return ex.Wrapf(removeErr, "removing imports from %s", toolFile)
		}
	}

	updateGenerateDirective(f, opts)

	if writeErr := ast.WriteFileAtomic(toolFile, f); writeErr != nil {
		return writeErr
	}

	_, ensureErr := ensureOtelcRequire(filepath.Dir(toolFile), util.Version)
	if ensureErr != nil {
		return ex.Wrapf(ensureErr, "ensuring otelc require in go.mod in %s", filepath.Dir(toolFile))
	}

	if tidyErr := runModTidy(ctx, filepath.Dir(toolFile)); tidyErr != nil {
		return ex.Wrapf(tidyErr, "running go mod tidy in %s", filepath.Dir(toolFile))
	}

	return nil
}

func updatePinnedProjects(
	ctx context.Context,
	toolFiles []string,
	opts PinOptions,
) error {
	logger := util.LoggerFromContext(ctx)
	prunedImports := make(map[string]map[string]bool, len(toolFiles))

	walkErr := walkInstrumentation(ctx, toolFiles,
		func(v *InstrumentationVisit) (bool, error) {
			pruneImport := func(reason error) {
				logger.WarnContext(ctx, "invalid instrumentation import",
					"importPath", v.Config.ImportPath,
					"toolFile", v.ToolFile,
					"reason", reason)
				_, _ = fmt.Fprintf(
					os.Stderr,
					"Invalid instrumentation import %s from %s: %v\n",
					v.Config.ImportPath,
					v.ToolFile,
					reason,
				)

				// We only prune imports from root tool files.
				if opts.Prune && slices.Contains(toolFiles, v.ToolFile) {
					if prunedImports[v.ToolFile] == nil {
						prunedImports[v.ToolFile] = make(map[string]bool)
					}
					prunedImports[v.ToolFile][v.Config.ImportPath] = true
				}
			}

			if v.Config.Error != nil {
				if errors.Is(v.Config.Error, ErrNotInstrumentation) {
					pruneImport(v.Config.Error)
					return false, nil
				}

				// Environment/module resolution problem.
				return false, v.Config.Error
			}

			// Also validate that all rule files in the import are valid.
			if opts.Validate {
				for _, ruleFile := range v.Config.RuleFiles {
					content, readErr := os.ReadFile(ruleFile)
					if readErr != nil {
						return false, ex.Wrapf(readErr, "reading %s", ruleFile)
					}

					if _, parseErr := parseRuleFromYaml(content); parseErr != nil {
						pruneImport(parseErr)
						return false, nil
					}
				}
			}

			// Always recurse into nested tool files when they exist.
			return true, nil
		},
	)
	if walkErr != nil {
		return walkErr
	}

	for _, toolFile := range toolFiles {
		if err := updateToolFile(ctx, toolFile, prunedImports[toolFile], opts); err != nil {
			return err
		}
	}

	return nil
}

func invalidInstrumentationImports(
	ctx context.Context,
	toolFiles []string,
	validateRules bool,
) (map[string]map[string]bool, error) {
	logger := util.LoggerFromContext(ctx)
	invalid := make(map[string]map[string]bool, len(toolFiles))

	err := walkInstrumentation(ctx, toolFiles, func(v *InstrumentationVisit) (bool, error) {
		var reason error
		if v.Config.Error != nil {
			if !errors.Is(v.Config.Error, ErrNotInstrumentation) {
				return false, v.Config.Error
			}
			reason = v.Config.Error
		} else if validateRules {
			for _, ruleFile := range v.Config.RuleFiles {
				content, readErr := os.ReadFile(ruleFile)
				if readErr != nil {
					return false, ex.Wrapf(readErr, "reading %s", ruleFile)
				}
				if _, parseErr := parseRuleFromYaml(content); parseErr != nil {
					reason = parseErr
					break
				}
			}
		}

		if reason == nil {
			return true, nil
		}

		logger.WarnContext(ctx, "invalid instrumentation import",
			"importPath", v.Config.ImportPath,
			"toolFile", v.ToolFile,
			"reason", reason)
		_, _ = fmt.Fprintf(os.Stderr, "Invalid instrumentation import %s from %s: %v\n",
			v.Config.ImportPath, v.ToolFile, reason)
		if slices.Contains(toolFiles, v.ToolFile) {
			if invalid[v.ToolFile] == nil {
				invalid[v.ToolFile] = make(map[string]bool)
			}
			invalid[v.ToolFile][v.Config.ImportPath] = true
		}
		return false, nil
	})

	return invalid, err
}

func backupOtelYAMLValidationFiles(configs []modulePinConfig) ([]fileBackup, error) {
	var backups []fileBackup
	for _, config := range configs {
		moduleDir := config.moduleDir
		for _, name := range []string{"go.mod", "go.sum", ToolFileCanonical, ToolFileAlias} {
			backup, err := backupFile(filepath.Join(moduleDir, name))
			if err != nil {
				return nil, err
			}
			backups = append(backups, backup)
		}
	}
	return backups, nil
}

type modulePinConfig struct {
	moduleDir string
	toolFile  string
	yamlFile  string
}

func addToolFileImports(toolFile string, imports map[string]bool) error {
	p := ast.NewAstParser()
	f, err := p.Parse(toolFile, parser.ParseComments)
	if err != nil {
		return ex.Wrapf(err, "parsing tool file %s", toolFile)
	}

	existing, err := loadToolFileImports(toolFile)
	if err != nil {
		return err
	}

	var importDecl *dst.GenDecl
	for _, decl := range f.Decls {
		genDecl, ok := decl.(*dst.GenDecl)
		if ok && genDecl.Tok == token.IMPORT {
			importDecl = genDecl
			break
		}
	}

	for _, importPath := range sortedImportPaths(imports) {
		if existing[importPath] {
			continue
		}
		spec := &dst.ImportSpec{
			Name: ast.Ident(ast.IdentIgnore),
			Path: &dst.BasicLit{Kind: token.STRING, Value: strconv.Quote(importPath)},
		}
		if importDecl == nil {
			importDecl = &dst.GenDecl{Tok: token.IMPORT}
			f.Decls = append([]dst.Decl{importDecl}, f.Decls...)
		}
		importDecl.Specs = append(importDecl.Specs, spec)
	}

	if err = ast.WriteFileAtomic(toolFile, f); err != nil {
		return ex.Wrapf(err, "writing %s", toolFile)
	}
	return nil
}

func materializeModuleConfigs(
	ctx context.Context,
	configs []modulePinConfig,
	opts PinOptions,
) ([]string, error) {
	toolFiles := make([]string, 0, len(configs))
	for _, config := range configs {
		var toolImports, yamlImports map[string]bool
		var err error
		if config.toolFile != "" {
			toolImports, err = loadToolFileImports(config.toolFile)
			if err != nil {
				return nil, err
			}
		}
		if config.yamlFile != "" {
			yamlImports, err = loadOtelYAMLImports(config.yamlFile)
			if err != nil {
				return nil, err
			}
		}
		imports := mergeImports(toolImports, yamlImports)

		toolFile := config.toolFile
		if toolFile == "" {
			toolFile = filepath.Join(config.moduleDir, ToolFileCanonical)
			generated := generateOtelInstrumentationGo(imports, opts)
			if writeErr := ast.WriteFileAtomic(toolFile, generated); writeErr != nil {
				return nil, ex.Wrapf(writeErr, "writing %s", toolFile)
			}
		} else if addErr := addToolFileImports(toolFile, yamlImports); addErr != nil {
			return nil, addErr
		}
		if _, ensureErr := ensureOtelcRequire(config.moduleDir, util.Version); ensureErr != nil {
			return nil, ex.Wrapf(ensureErr, "ensuring otelc require in go.mod in %s", config.moduleDir)
		}
		if syncErr := syncDeps(ctx, imports, config.moduleDir); syncErr != nil {
			return nil, ex.Wrapf(syncErr, "syncing dependencies in %s", config.moduleDir)
		}
		keepForDebug(ctx, toolFile)
		toolFiles = append(toolFiles, toolFile)
	}
	return toolFiles, nil
}

func applyOtelYAMLValidation(
	otelYAMLFiles map[string]string,
	yamlImportsByModule map[string]map[string]bool,
	invalid map[string]map[string]bool,
	opts PinOptions,
) error {
	for _, moduleDir := range sortedStringsMapKeys(otelYAMLFiles) {
		toolFile := filepath.Join(moduleDir, ToolFileCanonical)
		for importPath := range invalid[toolFile] {
			delete(yamlImportsByModule[moduleDir], importPath)
		}

		if opts.AutoPin {
			generated := generateOtelInstrumentationGo(yamlImportsByModule[moduleDir], opts)
			if writeErr := ast.WriteFileAtomic(toolFile, generated); writeErr != nil {
				return ex.Wrapf(writeErr, "writing %s", toolFile)
			}
		} else if opts.Prune {
			if writeErr := writeOtelYAMLImports(
				otelYAMLFiles[moduleDir], yamlImportsByModule[moduleDir],
			); writeErr != nil {
				return writeErr
			}
		}
	}
	return nil
}

func processOtelYAMLFiles(
	ctx context.Context,
	configs []modulePinConfig,
	opts PinOptions,
) (*PinResult, error) {
	if err := extractOtelcBundle(); err != nil {
		return nil, ex.Wrapf(err, "extracting otelc package")
	}

	var backups []fileBackup
	if !opts.AutoPin {
		var err error
		backups, err = backupOtelYAMLValidationFiles(configs)
		if err != nil {
			return nil, err
		}
	}

	otelYAMLFiles := make(map[string]string, len(configs))
	yamlImportsByModule := make(map[string]map[string]bool, len(configs))
	for _, config := range configs {
		otelYAMLFiles[config.moduleDir] = config.yamlFile
		yamlImports, loadErr := loadOtelYAMLImports(config.yamlFile)
		if loadErr != nil {
			return restoreOtelYAMLValidationFiles(nil, loadErr, backups)
		}
		yamlImportsByModule[config.moduleDir] = yamlImports
	}
	toolFiles, err := materializeModuleConfigs(ctx, configs, opts)
	if err != nil {
		return restoreOtelYAMLValidationFiles(nil, err, backups)
	}

	invalid, err := invalidInstrumentationImports(ctx, toolFiles, opts.Validate)
	if err != nil {
		return restoreOtelYAMLValidationFiles(nil, err, backups)
	}
	if err = applyOtelYAMLValidation(otelYAMLFiles, yamlImportsByModule, invalid, opts); err != nil {
		return restoreOtelYAMLValidationFiles(nil, err, backups)
	}

	return restoreOtelYAMLValidationFiles(&PinResult{}, nil, backups)
}

func generatePinnedProjects(ctx context.Context, moduleDirs map[string]bool, opts PinOptions) (*PinResult, error) {
	logger := util.LoggerFromContext(ctx)
	subcommand := opts.Subcommand
	if subcommand == "" {
		subcommand = subcmdBuild
	}

	// No tool file found? Try generating one.
	deps, findDepsErr := findDeps(ctx, subcommand, opts.Args)
	if findDepsErr != nil {
		return nil, ex.Wrapf(findDepsErr, "finding dependencies")
	}

	extractErr := extractOtelcBundle()
	if extractErr != nil {
		return nil, ex.Wrapf(extractErr, "extracting otelc package")
	}

	ruleset, err := loadMinimalRules(filepath.Join(util.GetBuildTempDir(), unzippedInstDir))
	if err != nil {
		return nil, ex.Wrapf(err, "loading instrumentation rules")
	}

	// We expect every built-in instrumentation module to be importable
	imports := matchInstrumentationImports(deps, ruleset)

	// Nothing to instrument? Warn and skip generating tool file.
	if len(imports) == 0 {
		_, _ = fmt.Fprintf(
			os.Stderr,
			"Warning: no instrumentations matched, checked %d dependencies. Skipping generating %s file.\n",
			len(deps),
			ToolFileCanonical,
		)
		logger.WarnContext(ctx, "no instrumentations matched, skipping generating tool file")

		// Ok to re-use deps here, because we do not run "go mod tidy".
		return &PinResult{AllDeps: deps}, nil
	}

	// Generate otel.instrumentation.go file with imports for all matched rules.
	f := generateOtelInstrumentationGo(imports, opts)
	for moduleDir := range moduleDirs {
		path := filepath.Join(moduleDir, ToolFileCanonical)
		if writeErr := ast.WriteFileAtomic(path, f); writeErr != nil {
			return nil, ex.Wrapf(writeErr, "writing %s", path)
		}

		if _, ensureErr := ensureOtelcRequire(moduleDir, util.Version); ensureErr != nil {
			return nil, ex.Wrapf(ensureErr, "ensuring otelc require in go.mod in %s", moduleDir)
		}

		if syncErr := syncDeps(ctx, imports, moduleDir); syncErr != nil {
			return nil, ex.Wrapf(syncErr, "syncing dependencies in %s", moduleDir)
		}

		keepForDebug(ctx, path)
	}

	// Intentionally return an empty PinResult
	// Since we ran syncDeps, the dependencies may have been updated
	// Therefore, we want to ensure we rerun findDeps in setup phase.
	return &PinResult{}, nil
}

func prepareVendoredBuild(ctx context.Context, logger *slog.Logger, args []string) ([]string, error) {
	if !vendoringActive(ctx, util.GetOtelcWorkDir()) {
		return args, nil
	}

	logger.InfoContext(ctx, "vendored project detected; building with -mod=mod")

	if err := os.Setenv("GOFLAGS", forceModMod(os.Getenv("GOFLAGS"))); err != nil {
		return nil, ex.Wrapf(err, "forcing module mode for vendored build")
	}

	return rewriteModVendor(args), nil
}

type PinOptions struct {
	// Whether to prune invalid imports within otel.instrumentation.go
	Prune bool
	// Whether to validate that all imports in otel.instrumentation.go contain valid rule
	Validate bool
	// Whether to have a //go:generate directive in otel.instrumentation.go
	Generate *bool
	// Args passed to go build/install/test in findDeps
	Args []string
	// Subcommand passed to go in findDeps (defaults to "build")
	Subcommand string
	// ModuleDirs is the set of module directories to search for tool files
	// If empty, module directories will be found using opts.Args
	ModuleDirs map[string]bool
	// AutoPin reports that Pin is running as part of the clean-room build flow.
	AutoPin bool
}

type PinResult struct {
	// AllDeps is a list of all dependencies found in the project (not just those with instrumentation).
	// It may not be always present, this can be used by later stages (setup) instead of
	// re-parsing compile commands again.
	AllDeps []*Dependency
}

// Pin generates or updates otel.instrumentation.go to pin instrumentation packages for the current module.
// It also returns a PinResult, which may optionally include a list of all dependencies found in the project
// (not just those with instrumentation). The PinResult can be used by later stages (setup) instead of
// re-parsing compile commands again.
func Pin(ctx context.Context, opts PinOptions) (*PinResult, error) {
	var result *PinResult
	err := withBuildLock(ctx, func(ctx context.Context) error {
		var pinErr error
		result, pinErr = pinLocked(ctx, opts)
		return pinErr
	})
	return result, err
}

func findPinModuleDirs(ctx context.Context, opts *PinOptions) (map[string]bool, error) {
	if len(opts.ModuleDirs) > 0 {
		return opts.ModuleDirs, nil
	}
	args, err := prepareVendoredBuild(ctx, util.LoggerFromContext(ctx), opts.Args)
	if err != nil {
		return nil, ex.Wrapf(err, "preparing vendored build")
	}
	opts.Args = args
	pkgs, err := getBuildPackages(ctx, opts.Args)
	if err != nil {
		return nil, ex.Wrapf(err, "getting build packages")
	}
	moduleDirs, err := pkgload.FindModuleDirs(ctx, pkgs)
	if err != nil {
		return nil, ex.Wrapf(err, "finding module directories")
	}
	return moduleDirs, nil
}

func discoverPinConfigs(moduleDirs map[string]bool) ([]modulePinConfig, map[string]bool, error) {
	configs := make([]modulePinConfig, 0, len(moduleDirs))
	unconfigured := make(map[string]bool)
	for _, moduleDir := range sortedStringsMapKeys(moduleDirs) {
		toolFile, err := findToolFile(moduleDir)
		if err != nil {
			return nil, nil, err
		}
		yamlFile, err := findInstrumentationYAMLFile(moduleDir)
		if err != nil {
			return nil, nil, err
		}
		if toolFile == "" && yamlFile == "" {
			unconfigured[moduleDir] = true
			continue
		}
		configs = append(configs, modulePinConfig{moduleDir: moduleDir, toolFile: toolFile, yamlFile: yamlFile})
	}
	return configs, unconfigured, nil
}

func processPinConfigs(
	ctx context.Context,
	configs []modulePinConfig,
	opts PinOptions,
) error {
	if !opts.AutoPin {
		yamlConfigs := make([]modulePinConfig, 0, len(configs))
		for _, config := range configs {
			if config.yamlFile != "" {
				yamlConfigs = append(yamlConfigs, config)
			}
		}
		if len(yamlConfigs) > 0 {
			if _, err := processOtelYAMLFiles(ctx, yamlConfigs, opts); err != nil {
				return err
			}
		}
	}
	materialized := configs
	if !opts.AutoPin {
		materialized = make([]modulePinConfig, 0, len(configs))
		for _, config := range configs {
			if config.yamlFile == "" {
				materialized = append(materialized, config)
			}
		}
	}
	if len(materialized) == 0 {
		return nil
	}
	if err := extractOtelcBundle(); err != nil {
		return ex.Wrapf(err, "extracting otelc package")
	}
	toolFiles, err := materializeModuleConfigs(ctx, materialized, opts)
	if err != nil {
		return err
	}
	return updatePinnedProjects(ctx, toolFiles, opts)
}

func pinLocked(ctx context.Context, opts PinOptions) (*PinResult, error) {
	moduleDirs, err := findPinModuleDirs(ctx, &opts)
	if err != nil {
		return nil, err
	}
	configs, unconfigured, err := discoverPinConfigs(moduleDirs)
	if err != nil {
		return nil, err
	}
	if len(configs) > 0 {
		if err = processPinConfigs(ctx, configs, opts); err != nil {
			return nil, err
		}
		return &PinResult{}, nil
	}

	if len(unconfigured) > 0 {
		return generatePinnedProjects(ctx, unconfigured, opts)
	}
	return &PinResult{}, nil
}

// AutoPin is a convenience function that automatically tracks generated/modified files before calling Pin
// in order to restore them after the build completes.
func AutoPin(ctx context.Context, moduleDirs map[string]bool, subcommand string, args []string) (*PinResult, error) {
	stateManager, found := StateManagerFromContext(ctx)
	if !found {
		return nil, ex.New("state manager not found in context")
	}

	backupFiles, getBackupErr := getBackupFiles(ctx, moduleDirs)
	if getBackupErr != nil {
		return nil, ex.Wrapf(getBackupErr, "getting backup files")
	}
	if trackErr := stateManager.TrackAll(backupFiles...); trackErr != nil {
		return nil, ex.Wrapf(trackErr, "tracking backup files")
	}

	pinResult, pinErr := Pin(ctx, PinOptions{
		Prune:      true,
		Args:       args,
		Subcommand: subcommand,
		ModuleDirs: moduleDirs,
		AutoPin:    true,
	})

	return pinResult, pinErr
}
