// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

package setup

import (
	"context"
	"errors"
	"fmt"
	"go/parser"
	"go/token"
	"io"
	"log/slog"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"

	"github.com/dave/dst"
	"go.yaml.in/yaml/v3"
	"golang.org/x/mod/modfile"
	"golang.org/x/mod/module"
	"golang.org/x/mod/semver"

	"go.opentelemetry.io/otelc/tool/ex"
	"go.opentelemetry.io/otelc/tool/internal/ast"
	"go.opentelemetry.io/otelc/tool/internal/manifest"
	"go.opentelemetry.io/otelc/tool/internal/pkgload"
	"go.opentelemetry.io/otelc/tool/internal/rule"
	"go.opentelemetry.io/otelc/tool/util"
)

func removeImports(f *dst.File, importPaths map[string]bool) error {
	decls := make([]dst.Decl, 0, len(f.Decls))

	for _, decl := range f.Decls {
		genDecl, isGenDecl := decl.(*dst.GenDecl)
		if !isGenDecl || genDecl.Tok != token.IMPORT {
			decls = append(decls, decl)
			continue
		}

		specs := genDecl.Specs[:0]
		for _, spec := range genDecl.Specs {
			importSpec, isImportSpec := spec.(*dst.ImportSpec)
			if !isImportSpec {
				specs = append(specs, spec)
				continue
			}

			path, err := strconv.Unquote(importSpec.Path.Value)
			if err != nil {
				return ex.Wrapf(err, "failed to unquote import path %s", importSpec.Path.Value)
			}

			// skip the import we want to remove
			if _, removeImport := importPaths[path]; removeImport {
				continue
			}

			specs = append(specs, spec)
		}

		if len(specs) == 0 {
			// entire import decl became empty
			continue
		}

		genDecl.Specs = specs
		decls = append(decls, genDecl)
	}

	f.Decls = decls
	return nil
}

func generateDirective(opts PinOptions) string {
	args := []string{
		"//go:generate",
		"go",
		"tool",
		util.OtelcToolExe,
		"pin",
		"--generate",
	}

	if !opts.Prune {
		args = append(args, "--prune=false")
	}
	if opts.Validate {
		args = append(args, "--validate")
	}

	return strings.Join(args, " ")
}

func updateGenerateDirective(f *dst.File, opts PinOptions) {
	// Nothing passed? Do not touch the directive at all.
	if opts.Generate == nil {
		return
	}

	comments := make([]string, 0, len(f.Decs.Start.All()))
	for _, comment := range f.Decs.Start.All() {
		// Drop any existing otelc pin directive. We will either
		// regenerate it or remove it entirely.
		const goGenerateDirectivePrefix = "//go:generate go tool " + util.OtelcToolExe + " pin"
		if strings.HasPrefix(comment, goGenerateDirectivePrefix) {
			continue
		}

		comments = append(comments, comment)
	}

	if *opts.Generate {
		comments = append(comments, generateDirective(opts))
	}

	f.Decs.Start.Clear()
	f.Decs.Start.Append(comments...)
}

func generateOtelInstrumentationGo(imports map[string]bool, opts PinOptions) *dst.File {
	// Create a slice of import paths and sort them
	importPaths := slices.Sorted(maps.Keys(imports))

	// Use the sorted import paths to create import specs
	importSpecs := make([]dst.Spec, 0, len(importPaths))
	for _, path := range importPaths {
		importSpecs = append(importSpecs, &dst.ImportSpec{
			Name: ast.Ident(ast.IdentIgnore),
			Path: &dst.BasicLit{
				Kind:  token.STRING,
				Value: strconv.Quote(path),
			},
		})
	}

	comments := ast.LineComments(
		"// This file is automatically generated by otelc pin for tracking instrumentations.",
		"// Additional instrumentation imports may be added manually.",
		"\n",
		"//go:build tools",
	)

	// If generate is explicitly enabled, or not set at all, include the //go:generate directive.
	if opts.Generate == nil || *opts.Generate {
		comments.Start.Append(generateDirective(opts))
	}

	f := &dst.File{
		Name: ast.Ident("tools"),
		Decs: dst.FileDecorations{
			NodeDecs: comments,
		},
	}
	if len(importSpecs) > 0 {
		f.Decls = []dst.Decl{&dst.GenDecl{Tok: token.IMPORT, Specs: importSpecs}}
	}
	return f
}

type otelYAMLConfig struct {
	Instrumentations []string `yaml:"instrumentations"`
}

func loadOtelYAMLImports(path string) (map[string]bool, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, ex.Wrapf(err, "reading %s", path)
	}

	var cfg otelYAMLConfig
	decoder := yaml.NewDecoder(strings.NewReader(string(data)))
	decoder.KnownFields(true)
	if err = decoder.Decode(&cfg); err != nil && !errors.Is(err, io.EOF) {
		return nil, ex.Wrapf(err, "parsing %s", path)
	}
	var extra any
	if err = decoder.Decode(&extra); err == nil {
		return nil, ex.Newf("%s: multiple YAML documents are not allowed", path)
	} else if !errors.Is(err, io.EOF) {
		return nil, ex.Wrapf(err, "parsing %s", path)
	}

	imports := make(map[string]bool, len(cfg.Instrumentations))
	for _, importPath := range cfg.Instrumentations {
		importPath = strings.TrimSpace(importPath)
		if importPath == "" {
			return nil, ex.Newf("%s: instrumentations must not contain empty import paths", path)
		}
		imports[importPath] = true
	}
	return imports, nil
}

func writeOtelYAMLImports(path string, imports map[string]bool) error {
	data, err := yaml.Marshal(&otelYAMLConfig{Instrumentations: slices.Sorted(maps.Keys(imports))})
	if err != nil {
		return ex.Wrapf(err, "marshalling %s", path)
	}
	info, err := os.Stat(path)
	if err != nil {
		return ex.Wrapf(err, "stating %s", path)
	}
	if err = util.WriteFileAtomic(path, data, info.Mode().Perm()); err != nil {
		return ex.Wrapf(err, "writing %s", path)
	}
	return nil
}

func ensureOtelcRequireVersion(f *modfile.File, version string) (bool, error) {
	if !semver.IsValid(version) || version == "v0.0.0" || module.IsPseudoVersion(version) {
		return false, nil
	}

	for _, req := range f.Require {
		if req.Mod.Path != util.OtelcRoot {
			continue
		}

		if semver.Compare(req.Mod.Version, version) >= 0 {
			return false, nil
		}
		break
	}

	if err := f.AddRequire(util.OtelcRoot, version); err != nil {
		return false, ex.Wrap(err)
	}

	return true, nil
}

func ensureOtelcRequire(moduleDir, version string) (bool, error) {
	goModPath := filepath.Join(moduleDir, goModFileName)
	data, err := os.ReadFile(goModPath)
	if err != nil {
		return false, ex.Wrap(err)
	}

	f, err := modfile.Parse(goModPath, data, nil)
	if err != nil {
		return false, ex.Wrap(err)
	}

	modified := false

	hasTool := false
	for _, tool := range f.Tool {
		if tool.Path == util.OtelcToolCmdRoot {
			hasTool = true
			break
		}
	}

	if !hasTool {
		if addErr := f.AddTool(util.OtelcToolCmdRoot); addErr != nil {
			return false, ex.Wrap(addErr)
		}
		modified = true
	}

	added, ensureErr := ensureOtelcRequireVersion(f, version)
	if ensureErr != nil {
		return false, ensureErr
	}
	modified = modified || added

	if !modified {
		return false, nil
	}

	if writeErr := writeGoMod(goModPath, f); writeErr != nil {
		return false, writeErr
	}

	return true, nil
}

func matchInstrumentationImports(
	deps []*Dependency,
	ruleset manifest.Manifest,
	warn func(msg string, args ...any),
) map[string]bool {
	imports := make(map[string]bool)

	// Record the first unresolved-version skip per instrumentation module.
	// Warnings are emitted after matching so we only complain when the module
	// was not imported by any other rule/dep (avoids false positives).
	skipped := make(map[string]unresolvedSkip)

	// Match only on target + version.
	for _, dep := range deps {
		for _, entry := range ruleset {
			tm := instrumentationRuleMatchesDep(dep, entry)
			if tm.isRoot {
				imports[entry.ModulePath] = true
				continue
			}
			if !tm.matched {
				continue
			}
			if !util.VersionInRange(dep.Version, entry.VersionRange) {
				recordUnresolvedSkip(skipped, entry.ModulePath, dep, entry.VersionRange)
				continue
			}
			imports[entry.ModulePath] = true
		}
	}

	emitUnresolvedSkipWarnings(warn, imports, skipped)
	return imports
}

type unresolvedSkip struct {
	dep          string
	versionRange string
}

type instrumentationTargetMatch struct {
	matched bool
	isRoot  bool
}

// instrumentationRuleMatchesDep reports whether r's target matches dep.
// Root targets always pin the instrumentation module.
func instrumentationRuleMatchesDep(dep *Dependency, entry manifest.Entry) instrumentationTargetMatch {
	switch {
	case rule.IsRootTarget(entry.Target):
		return instrumentationTargetMatch{matched: true, isRoot: true}
	case rule.IsGlobTarget(entry.Target):
		return instrumentationTargetMatch{matched: rule.MatchGlobTarget(entry.Target, dep.ImportPath)}
	default:
		return instrumentationTargetMatch{matched: entry.Target == dep.ImportPath}
	}
}

func recordUnresolvedSkip(
	skipped map[string]unresolvedSkip,
	modPath string,
	dep *Dependency,
	versionRange string,
) {
	if !unresolvedVersionSkip(dep.Version, versionRange) {
		return
	}
	if _, ok := skipped[modPath]; ok {
		return
	}
	skipped[modPath] = unresolvedSkip{
		dep:          dep.ImportPath,
		versionRange: versionRange,
	}
}

func emitUnresolvedSkipWarnings(
	warn func(msg string, args ...any),
	imports map[string]bool,
	skipped map[string]unresolvedSkip,
) {
	if warn == nil {
		return
	}
	for modPath, s := range skipped {
		if imports[modPath] {
			continue
		}
		warnUnresolvedVersionSkip(warn, s.dep, s.versionRange,
			"instrumentation", modPath,
		)
	}
}

func updateToolFile(ctx context.Context, toolFile string, prunedImports map[string]bool, opts PinOptions) error {
	p := ast.NewAstParser()

	f, parseErr := p.Parse(toolFile, parser.ParseComments)
	if parseErr != nil {
		return parseErr
	}

	if len(prunedImports) > 0 {
		if removeErr := removeImports(f, prunedImports); removeErr != nil {
			return removeErr
		}
	}

	updateGenerateDirective(f, opts)

	if writeErr := ast.WriteFileAtomic(toolFile, f); writeErr != nil {
		return writeErr
	}

	_, ensureErr := ensureOtelcRequire(filepath.Dir(toolFile), util.Version)
	if ensureErr != nil {
		return ensureErr
	}

	return runModTidy(ctx, filepath.Dir(toolFile))
}

func validateRuleFiles(ctx context.Context, ruleFiles []string) error {
	for _, ruleFile := range ruleFiles {
		content, err := os.ReadFile(ruleFile)
		if err != nil {
			return ex.Wrapf(err, "reading %s", ruleFile)
		}
		doc, err := rule.ParseFile(content)
		if err != nil {
			return ex.Wrapf(err, "parsing rule file %s", ruleFile)
		}
		if err = checkRuleFileVersion(ctx, ruleFile, doc, util.Version); err != nil {
			return err
		}
		if _, err = doc.Rules(); err != nil {
			return err
		}
	}
	return nil
}

func updatePinnedProjects(
	ctx context.Context,
	toolFiles []string,
	opts PinOptions,
) error {
	logger := util.LoggerFromContext(ctx)
	prunedImports := make(map[string]map[string]bool, len(toolFiles))

	walkErr := walkInstrumentation(ctx, toolFiles,
		func(v *instrumentationVisit) (bool, error) {
			pruneImport := func(reason error) {
				logger.WarnContext(ctx, "invalid instrumentation import",
					"importPath", v.Config.ImportPath,
					"toolFile", v.ToolFile,
					"reason", reason)
				_, _ = fmt.Fprintf(
					os.Stderr,
					"Invalid instrumentation import %s from %s: %v\n",
					v.Config.ImportPath,
					v.ToolFile,
					reason,
				)

				// We only prune imports from root tool files.
				if opts.Prune && slices.Contains(toolFiles, v.ToolFile) {
					if prunedImports[v.ToolFile] == nil {
						prunedImports[v.ToolFile] = make(map[string]bool)
					}
					prunedImports[v.ToolFile][v.Config.ImportPath] = true
				}
			}

			if v.Config.Error != nil {
				if errors.Is(v.Config.Error, errNotInstrumentation) {
					pruneImport(v.Config.Error)
					return false, nil
				}

				// Environment/module resolution problem.
				return false, v.Config.Error
			}

			// Also validate that all rule files in the import are valid.
			if opts.Validate {
				if validateErr := validateRuleFiles(ctx, v.Config.RuleFiles); validateErr != nil {
					pruneImport(validateErr)
					return false, nil
				}
			}

			// Always recurse into nested tool files when they exist.
			return true, nil
		},
	)
	if walkErr != nil {
		return walkErr
	}

	for _, toolFile := range toolFiles {
		if err := updateToolFile(ctx, toolFile, prunedImports[toolFile], opts); err != nil {
			return err
		}
	}

	return nil
}

type modulePinConfig struct {
	moduleDir string
	toolFile  string
	yamlFile  string
}

type yamlPinState struct {
	config   modulePinConfig
	imports  map[string]bool
	toolFile string
}

func loadYAMLStates(configs []modulePinConfig) ([]yamlPinState, error) {
	states := make([]yamlPinState, 0, len(configs))
	for _, config := range configs {
		imports, err := loadOtelYAMLImports(config.yamlFile)
		if err != nil {
			return nil, err
		}
		states = append(states, yamlPinState{config: config, imports: imports})
	}
	return states, nil
}

func yamlStateManager(ctx context.Context, autoPin bool) (*stateManager, error) {
	if !autoPin {
		return newStateManager(), nil
	}
	manager, found := stateManagerFromContext(ctx)
	if !found {
		return nil, ex.New("state manager not found in context")
	}
	return manager, nil
}

func trackYAMLConfigFiles(manager *stateManager, configs []modulePinConfig) error {
	for _, config := range configs {
		for _, name := range []string{goModFileName, goSumFileName, toolFileCanonical, toolFileAlias} {
			if err := manager.Track(filepath.Join(config.moduleDir, name)); err != nil {
				return err
			}
		}
	}
	return nil
}

func pruneYAMLStates(states []yamlPinState, invalid map[string]map[string]bool) {
	for i := range states {
		for importPath := range invalid[states[i].toolFile] {
			delete(states[i].imports, importPath)
		}
	}
}

func finalizeAutoPinYAML(ctx context.Context, states []yamlPinState, opts PinOptions, manager *stateManager) error {
	for _, state := range states {
		if err := ast.WriteFileAtomic(state.toolFile, generateOtelInstrumentationGo(state.imports, opts)); err != nil {
			return ex.Join(ex.Wrapf(err, "writing %s", state.toolFile), manager.Revert())
		}
		if err := runModTidy(ctx, state.config.moduleDir); err != nil {
			return ex.Join(ex.Wrapf(err, "running go mod tidy in %s", state.config.moduleDir), manager.Revert())
		}
	}
	return nil
}

func finalizeStandaloneYAML(states []yamlPinState, opts PinOptions, manager *stateManager) error {
	if err := manager.Revert(); err != nil {
		return err
	}
	if err := manager.Discard(); err != nil {
		return err
	}
	if !opts.Prune {
		return nil
	}
	for _, state := range states {
		if err := writeOtelYAMLImports(state.config.yamlFile, state.imports); err != nil {
			return err
		}
	}
	return nil
}

func materializeYAMLConfigs(ctx context.Context, configs []modulePinConfig, opts PinOptions) ([]string, error) {
	toolFiles := make([]string, 0, len(configs))
	for _, config := range configs {
		imports, err := loadOtelYAMLImports(config.yamlFile)
		if err != nil {
			return nil, err
		}
		toolFile := filepath.Join(config.moduleDir, toolFileCanonical)
		if err = ast.WriteFileAtomic(toolFile, generateOtelInstrumentationGo(imports, opts)); err != nil {
			return nil, ex.Wrapf(err, "writing %s", toolFile)
		}
		if _, err = ensureOtelcRequire(config.moduleDir, util.Version); err != nil {
			return nil, ex.Wrapf(err, "ensuring otelc require in go.mod in %s", config.moduleDir)
		}
		if err = syncDeps(ctx, imports, config.moduleDir); err != nil {
			return nil, ex.Wrapf(err, "syncing dependencies in %s", config.moduleDir)
		}
		keepForDebug(ctx, toolFile)
		toolFiles = append(toolFiles, toolFile)
	}
	return toolFiles, nil
}

func invalidInstrumentationImports(
	ctx context.Context,
	toolFiles []string,
	validate bool,
) (map[string]map[string]bool, error) {
	invalid := make(map[string]map[string]bool, len(toolFiles))
	err := walkInstrumentation(ctx, toolFiles, func(v *instrumentationVisit) (bool, error) {
		var reason error
		if v.Config.Error != nil {
			if !errors.Is(v.Config.Error, errNotInstrumentation) {
				return false, v.Config.Error
			}
			reason = v.Config.Error
		} else if validate {
			if validateErr := validateRuleFiles(ctx, v.Config.RuleFiles); validateErr != nil {
				reason = validateErr
			}
		}
		if reason == nil {
			return true, nil
		}
		util.LoggerFromContext(ctx).WarnContext(ctx, "invalid instrumentation import",
			"importPath", v.Config.ImportPath, "toolFile", v.ToolFile, "reason", reason)
		_, _ = fmt.Fprintf(os.Stderr, "Invalid instrumentation import %s from %s: %v\n",
			v.Config.ImportPath, v.ToolFile, reason)
		if slices.Contains(toolFiles, v.ToolFile) {
			if invalid[v.ToolFile] == nil {
				invalid[v.ToolFile] = make(map[string]bool)
			}
			invalid[v.ToolFile][v.Config.ImportPath] = true
		}
		return false, nil
	})
	return invalid, err
}

func processYAMLConfigs(ctx context.Context, configs []modulePinConfig, opts PinOptions) error {
	states, err := loadYAMLStates(configs)
	if err != nil {
		return err
	}
	manager, err := yamlStateManager(ctx, opts.AutoPin)
	if err != nil {
		return err
	}
	if err = trackYAMLConfigFiles(manager, configs); err != nil {
		return err
	}

	toolFiles, err := materializeYAMLConfigs(ctx, configs, opts)
	if err != nil {
		return ex.Join(err, manager.Revert())
	}
	for i := range states {
		states[i].toolFile = toolFiles[i]
	}
	invalid, err := invalidInstrumentationImports(ctx, toolFiles, opts.Validate)
	if err != nil {
		return ex.Join(err, manager.Revert())
	}
	pruneYAMLStates(states, invalid)
	if opts.AutoPin {
		return finalizeAutoPinYAML(ctx, states, opts, manager)
	}
	return finalizeStandaloneYAML(states, opts, manager)
}

func discoverPinConfigs(moduleDirs map[string]bool) ([]modulePinConfig, map[string]bool, error) {
	configs := make([]modulePinConfig, 0, len(moduleDirs))
	unconfigured := make(map[string]bool)
	for _, moduleDir := range slices.Sorted(maps.Keys(moduleDirs)) {
		toolFile, err := findToolFile(moduleDir)
		if err != nil {
			return nil, nil, err
		}
		if toolFile != "" {
			configs = append(configs, modulePinConfig{moduleDir: moduleDir, toolFile: toolFile})
			continue
		}
		yamlFile, err := findInstrumentationYAMLFile(moduleDir)
		if err != nil {
			return nil, nil, err
		}
		if yamlFile == "" {
			unconfigured[moduleDir] = true
			continue
		}
		configs = append(configs, modulePinConfig{moduleDir: moduleDir, yamlFile: yamlFile})
	}
	return configs, unconfigured, nil
}

func generatePinnedProjects(ctx context.Context, moduleDirs map[string]bool, opts PinOptions) (*PinResult, error) {
	logger := util.LoggerFromContext(ctx)
	subcommand := opts.Subcommand
	if subcommand == "" {
		subcommand = subcmdBuild
	}

	// No tool file found? Try generating one.
	deps, findDepsErr := findDeps(ctx, subcommand, opts.Args)
	if findDepsErr != nil {
		return nil, findDepsErr
	}

	ruleset, err := manifest.Load()
	if err != nil {
		return nil, ex.Wrapf(err, "loading instrumentation manifest")
	}

	// We expect every built-in instrumentation module to be importable
	imports := matchInstrumentationImports(deps, ruleset, func(msg string, args ...any) {
		logger.WarnContext(ctx, msg, args...)
	})

	// Nothing to instrument? Warn and skip generating tool file.
	if len(imports) == 0 {
		_, _ = fmt.Fprintf(
			os.Stderr,
			"Warning: no instrumentations matched, checked %d dependencies. Skipping generating %s file.\n",
			len(deps),
			toolFileCanonical,
		)
		logger.WarnContext(ctx, "no instrumentations matched, skipping generating tool file")

		// Ok to re-use deps here, because we do not run "go mod tidy".
		return &PinResult{AllDeps: deps}, nil
	}

	// Generate otel.instrumentation.go file with imports for all matched rules.
	f := generateOtelInstrumentationGo(imports, opts)
	dirs := slices.Sorted(maps.Keys(moduleDirs))
	for _, moduleDir := range dirs {
		path := filepath.Join(moduleDir, toolFileCanonical)
		if writeErr := ast.WriteFileAtomic(path, f); writeErr != nil {
			return nil, ex.Wrapf(writeErr, "writing %s", path)
		}

		if _, ensureErr := ensureOtelcRequire(moduleDir, util.Version); ensureErr != nil {
			return nil, ensureErr
		}

		if syncErr := syncDeps(ctx, imports, moduleDir); syncErr != nil {
			return nil, syncErr
		}

		keepForDebug(ctx, path)
	}

	// Intentionally return an empty PinResult
	// Since we ran syncDeps, the dependencies may have been updated
	// Therefore, we want to ensure we rerun findDeps in setup phase.
	return &PinResult{}, nil
}

func prepareVendoredBuild(ctx context.Context, logger *slog.Logger, args []string) ([]string, error) {
	if !vendoringActive(ctx, util.GetOtelcWorkDir()) {
		return args, nil
	}

	logger.InfoContext(ctx, "vendored project detected; building with -mod=mod")

	if err := os.Setenv("GOFLAGS", forceModMod(os.Getenv("GOFLAGS"))); err != nil {
		return nil, ex.Wrapf(err, "forcing module mode for vendored build")
	}

	return rewriteModVendor(args), nil
}

type PinOptions struct {
	// Whether to prune invalid imports within otel.instrumentation.go
	Prune bool
	// Whether to validate that all imports in otel.instrumentation.go contain valid rule
	Validate bool
	// Whether to have a //go:generate directive in otel.instrumentation.go
	Generate *bool
	// Args passed to go build/install/test in findDeps
	Args []string
	// Subcommand passed to go in findDeps (defaults to "build")
	Subcommand string
	// ModuleDirs is the set of module directories to search for tool files
	// If empty, module directories will be found using opts.Args
	ModuleDirs map[string]bool
	// AutoPin reports that Pin is running as part of the clean-room build flow.
	AutoPin bool
}

type PinResult struct {
	// AllDeps is a list of all dependencies found in the project (not just those with instrumentation).
	// It may not be always present, this can be used by later stages (setup) instead of
	// re-parsing compile commands again.
	AllDeps []*Dependency
}

// Pin generates or updates otel.instrumentation.go to pin instrumentation packages for the current module.
// It also returns a PinResult, which may optionally include a list of all dependencies found in the project
// (not just those with instrumentation). The PinResult can be used by later stages (setup) instead of
// re-parsing compile commands again.
func Pin(ctx context.Context, opts PinOptions) (*PinResult, error) {
	var result *PinResult
	err := withBuildLock(ctx, func(ctx context.Context) error {
		var pinErr error
		result, pinErr = pinLocked(ctx, opts)
		return pinErr
	})
	return result, err
}

func pinModuleDirs(ctx context.Context, opts *PinOptions) (map[string]bool, error) {
	if len(opts.ModuleDirs) > 0 {
		return opts.ModuleDirs, nil
	}
	args, err := prepareVendoredBuild(ctx, util.LoggerFromContext(ctx), opts.Args)
	if err != nil {
		return nil, err
	}
	opts.Args = args
	pkgs, err := getBuildPackages(ctx, opts.Args)
	if err != nil {
		return nil, err
	}
	return pkgload.FindModuleDirs(ctx, pkgs)
}

func partitionPinConfigs(configs []modulePinConfig) ([]string, []modulePinConfig) {
	toolFiles := make([]string, 0, len(configs))
	yamlConfigs := make([]modulePinConfig, 0, len(configs))
	for _, config := range configs {
		if config.toolFile != "" {
			toolFiles = append(toolFiles, config.toolFile)
		} else {
			yamlConfigs = append(yamlConfigs, config)
		}
	}
	return toolFiles, yamlConfigs
}

func processConfiguredModules(ctx context.Context, configs []modulePinConfig, opts PinOptions) error {
	toolFiles, yamlConfigs := partitionPinConfigs(configs)
	if len(toolFiles) > 0 {
		if err := updatePinnedProjects(ctx, toolFiles, opts); err != nil {
			return err
		}
	}
	if len(yamlConfigs) > 0 {
		return processYAMLConfigs(ctx, yamlConfigs, opts)
	}
	return nil
}

func pinLocked(ctx context.Context, opts PinOptions) (*PinResult, error) {
	moduleDirs, err := pinModuleDirs(ctx, &opts)
	if err != nil {
		return nil, err
	}

	configs, unconfigured, err := discoverPinConfigs(moduleDirs)
	if err != nil {
		return nil, err
	}
	if err = processConfiguredModules(ctx, configs, opts); err != nil {
		return nil, err
	}

	if len(unconfigured) > 0 {
		result, generateErr := generatePinnedProjects(ctx, unconfigured, opts)
		if generateErr != nil {
			return nil, generateErr
		}
		if len(configs) > 0 {
			// Configured modules may have changed dependencies, so setup must
			// rediscover them instead of reusing the pre-materialization result.
			return &PinResult{}, nil
		}
		return result, nil
	}
	return &PinResult{}, nil
}

// autoPin is a convenience function that automatically tracks generated/modified files before calling Pin
// in order to restore them after the build completes.
func autoPin(ctx context.Context, moduleDirs map[string]bool, subcommand string, args []string) (*PinResult, error) {
	stateManager, found := stateManagerFromContext(ctx)
	if !found {
		return nil, ex.New("state manager not found in context")
	}

	backupFiles, getBackupErr := getBackupFiles(ctx, moduleDirs)
	if getBackupErr != nil {
		return nil, getBackupErr
	}
	if trackErr := stateManager.TrackAll(backupFiles...); trackErr != nil {
		return nil, trackErr
	}

	pinResult, pinErr := Pin(ctx, PinOptions{
		Prune:      true,
		Args:       args,
		Subcommand: subcommand,
		ModuleDirs: moduleDirs,
		AutoPin:    true,
	})

	return pinResult, pinErr
}
