{
 "title": "OpenTelemetry APM",
 "description": "A language-agnostic application performance management(APM) with OpenTelemetry, Grafana, and Prometheus.",
 "tags": [
  "apm",
  "opentelemetry",
  "services",
  "metrics",
  "traces"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "label_values(traces_span_metrics_duration_milliseconds_count, service_name)"
    }
   },
   {
    "name": "route",
    "label": "Route",
    "query": {
     "query": "label_values(traces_span_metrics_duration_milliseconds_count, http_route)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Request",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(traces_span_metrics_duration_milliseconds_count{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$app\"}) by(service_name)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(traces_span_metrics_duration_milliseconds_count{service_name=\"$app\", span_kind=\"SPAN_KIND_SERVER\", status_code=~\"^2.*\"}) by(status_code)",
     "legendFormat": "Http Status 2XX"
    },
    {
     "expr": "sum(traces_span_metrics_duration_milliseconds_count{service_name=\"$app\", span_kind=\"SPAN_KIND_SERVER\", status_code=~\"^3.*\"}) by(status_code)",
     "legendFormat": "Http Status 3XX"
    },
    {
     "expr": "sum(traces_span_metrics_duration_milliseconds_count{service_name=\"$app\", span_kind=\"SPAN_KIND_SERVER\", status_code=~\"^4.*\"}) by(status_code)",
     "legendFormat": "Http Status 4XX"
    },
    {
     "expr": "sum(traces_span_metrics_duration_milliseconds_count{service_name=\"$app\", span_kind=\"SPAN_KIND_SERVER\", status_code=~\"^5.*\"}) by(status_code)",
     "legendFormat": "Http Status 5XX"
    }
   ]
  },
  {
   "title": "Request Distribution",
   "type": "piechart",
   "description": "request amount distribution",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(traces_span_metrics_duration_milliseconds_count{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$app\"}) by(span_name)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Loading Distribution",
   "type": "piechart",
   "description": "cumulative latency distribution",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(traces_span_metrics_duration_milliseconds_sum{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$app\"}) by(span_name)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Overall Request Rate",
   "type": "gauge",
   "description": "overall request rate per minute over last 3 minutes",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_duration_milliseconds_count{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$app\"}[3m])*60)"
    }
   ]
  },
  {
   "title": "Overall Error Rate",
   "type": "gauge",
   "description": "percentage of HTTP status 5xx in all requests",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(traces_span_metrics_duration_milliseconds_count{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$app\", status_code=~\"5.*|\"})/sum(traces_span_metrics_duration_milliseconds_count{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$app\"})"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "request rate per minute over last 3 minutes",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_duration_milliseconds_count{service_name=\"$app\", span_kind=\"SPAN_KIND_SERVER\"}[3m])*60)  by(span_name)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "PR95 Latency",
   "type": "timeseries",
   "description": "PR95 latency over last 3 minutes",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$app\"}[3m])) by (le, span_name))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "bargauge",
   "description": "by route and http status code",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(traces_span_metrics_duration_milliseconds_sum{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$app\", status_code!=\"\"} / traces_span_metrics_duration_milliseconds_count{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$app\", status_code!=\"\"})",
     "legendFormat": "[{{status_code}}] {{span_name}}"
    }
   ]
  },
  {
   "title": "Details",
   "type": "table",
   "description": "Details of each API",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_duration_milliseconds_count{service_name=\"$app\", span_kind=\"SPAN_KIND_SERVER\"}[3m])*60) by(service_name, http_method, http_route)"
    },
    {
     "expr": "sum(rate(traces_span_metrics_duration_milliseconds_count{service_name=\"$app\", span_kind=\"SPAN_KIND_SERVER\"}[3m])*60) by(service_name, http_method, http_route)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_span_metrics_duration_milliseconds_bucket{service_name=\"$app\", span_kind=\"SPAN_KIND_SERVER\"}[3m])) by (le, service_name, http_method, http_route))"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_span_metrics_duration_milliseconds_bucket{service_name=\"$app\", span_kind=\"SPAN_KIND_SERVER\"}[3m])) by (le, service_name, http_method, http_route))"
    },
    {
     "expr": "sum(traces_span_metrics_duration_milliseconds_count{service_name=\"$app\", span_kind=\"SPAN_KIND_SERVER\", status_code!~\"2.*|3.*\"}) by(service_name, http_method, http_route) / sum(traces_span_metrics_duration_milliseconds_count{service_name=\"$app\", span_kind=\"SPAN_KIND_SERVER\"}) by(service_name, http_method, http_route)"
    },
    {
     "expr": "sum(traces_span_metrics_duration_milliseconds_count{service_name=\"$app\", span_kind=\"SPAN_KIND_SERVER\", status_code!~\"2.*|3.*\"}) by(service_name, http_method, http_route) / sum(traces_span_metrics_duration_milliseconds_count{service_name=\"$app\", span_kind=\"SPAN_KIND_SERVER\"}) by(service_name, http_method, http_route)"
    }
   ]
  }
 ]
}