// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// This file is automatically generated by otelc pin for tracking instrumentations.
// Additional instrumentation imports may be added manually.

//go:build tools

package tools

import (
	_ "github.com/open-telemetry/opentelemetry-go-compile-instrumentation/tool/cmd"

	_ "github.com/open-telemetry/opentelemetry-go-compile-instrumentation/demo/app/basic/instrumentation"
)
