name: Check Typos

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  check-typos:
    name: Check Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0

      - name: Check Typos
        uses: crate-ci/typos@626c4bedb751ce0b7f03262ca97ddda9a076ae1c  # v1.39.2
