name: Check Typos

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  check-typos:
    name: Check Typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - uses: crate-ci/typos@9066e9940a8a05b98fb4733c62a726f83c9e57f8  # v1.43.3
        with:
          config: .config/typos.toml
