name: Debug Bundle Tmp
on:
  push:
    branches:
      - dario.castane/pr-1292-go-1-25-deps-d70919
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - run: go version
      - run: make package
      - uses: actions/upload-artifact@v4
        with:
          name: bundle-debug
          path: tool/data/otelc-bundle.tgz
