name: Linters
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
env:
  # TODO: Configure dependabot or renovate to update this version.
  GOLANGCI_LINT_VERSION: v2.1.6

jobs:
  golangci:
    strategy:
      matrix:
        go: [oldstable, stable]
    name: Format and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: ${{ matrix.go }}
          cache-dependency-path: "**/go.mod"
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${{ env.GOLANGCI_LINT_VERSION }}
      - name: Check Format
        run: |
          golangci-lint fmt --diff
      - name: Lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
      - name: Check Typos
        uses: crate-ci/typos@85f62a8a84f939ae994ab3763f01a0296d61a7ee # v1.36.2
