name: Linters
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    strategy:
      matrix:
        go: [oldstable, stable]
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache-dependency-path: "**/go.mod"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0
